name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build fat jar
        run: ./gradlew --no-daemon clean shadowJar

      - name: Generate checksums
        run: |
          cd build/libs
          for f in *.jar; do shasum -a 256 "$f" > "$f.sha256"; done

      - name: Upload artifact to run
        uses: actions/upload-artifact@v4
        with:
          name: specops-${{ github.ref_name }}
          path: |
            build/libs/*.jar
            build/libs/*.sha256
          if-no-files-found: error
          retention-days: 7

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: "SpecOps ${{ github.ref_name }}"
          generate_release_notes: true
          files: build/libs/*.jar
